Update 1.1 - Hotfixes

diff --git a/maya b/maya
--- a/maya
+++ b/maya
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-# Written by @sakaki91 (using VIM), heavily inspired by Ports.
+# Written by @sakaki91, heavily inspired by Ports.
 
-MAYA_VERSION=1.0
+MAYA_VERSION=1.1
 MAYA_TREE=/usr/local/share/maya
 
 function rootCheck(){
@@ -11,12 +11,12 @@ function rootCheck(){
 
 function dependencieCheck(){
 	if [[ ! -z $DEPENDENCIES ]]; then
-        	for dep in "${DEPENDENCIES[@]}"; do
-	            if ! command -v "$dep" >/dev/null 2>&1; then
-        	        printf "\e[0;91merror:\033[0m $dep is not installed.\n" && exit
-	            fi
-        	done
-    	fi
+        for dep in "${DEPENDENCIES[@]}"; do
+	    	if ! command -v "$dep" >/dev/null 2>&1; then
+        	    printf "\e[0;91merror:\033[0m $dep is not installed.\n" && exit
+	        fi
+        done
+    fi
 }
 
 function binaryExCheck(){
@@ -27,45 +27,45 @@ function binaryExCheck(){
 case $1 in
 	"--help"|"-h")
 		printf "\e[1moperations:\e[0m\n%-25s %0s\n" " -h  | --help" ":: show this message."
-	        printf "%-25s %0s\n" " -v  | --version" ":: shows the version."
-        	printf "%-25s %0s\n" " -a  | --about" ":: view the metadata (version, name, and description) of a package."
-	        printf "%-25s %0s\n" " -l  | --list" ":: shows all binaries available for installation."
-        	printf "%-25s %0s\n" " -li | --list-installed" ":: it shows everything that maya has installed."
-	        printf "%-25s %0s\n" " -cl | --clean" ":: clears the /tmp/maya directory."
-        	printf "%-25s %0s\n" " -sy | --sync-maya" ":: update maya and recipes by pulling directly from the git."
-	        printf "%-25s %0s\n" " -in | --install" ":: install a binary."
-        	printf "%-25s %0s\n\n" " -rm | --remove" ":: remove a binary."
-	        printf "\e[1musage: maya 'operation' [...]\e[0m\n"
-    	;;
-    	"--version"|"-v") printf "maya-$MAYA_VERSION\n" ;;
-    	"--about"|"-a") 
-     		binaryExCheck "$2"
-	        source "$MAYA_TREE/pkg/$2" && printf "\e[1m%-25s\e[0m %10s\n" "$NAME :: $VERSION" "$DESCRIPTION"
-    	;;
-    	"--list"|"-l") 
-	    	[[ -z $2 ]] && printf "\e[0;95m$(ls $MAYA_TREE/pkg -p -1 | grep -v /)\e[0m\n" && exit
-	    	[[ ! -z $2 ]] && printf "\e[0;95m$(ls $MAYA_TREE/pkg -p -1 | grep -v / | grep $2)\e[0m\n" && exit
+	    printf "%-25s %0s\n" " -v  | --version" ":: shows the version."
+        printf "%-25s %0s\n" " -a  | --about" ":: view the metadata (version, name, and description) of a package."
+	    printf "%-25s %0s\n" " -l  | --list" ":: shows all binaries available for installation."
+        printf "%-25s %0s\n" " -li | --list-installed" ":: it shows everything that maya has installed."
+	    printf "%-25s %0s\n" " -cl | --clean" ":: clears the /tmp/maya directory."
+        printf "%-25s %0s\n" " -sy | --sync-maya" ":: update maya and recipes by pulling directly from the git."
+	    printf "%-25s %0s\n" " -in | --install" ":: install a binary."
+        printf "%-25s %0s\n\n" " -rm | --remove" ":: remove a binary."
+	    printf "\e[1musage: maya 'operation' [...]\e[0m\n"
+    ;;
+    "--version"|"-v") printf "maya-$MAYA_VERSION\n" ;;
+    "--about"|"-a") 
+     	binaryExCheck "$2"
+	    source "$MAYA_TREE/pkg/$2" && printf "\e[1m%-25s\e[0m %10s\n" "$NAME :: $VERSION" "$DESCRIPTION"
+    ;;
+    "--list"|"-l") 
+	   	[[ -z $2 ]] && printf "\e[0;95m$(ls $MAYA_TREE/pkg -p -1 | grep -v /)\e[0m\n" && exit
+	   	[[ ! -z $2 ]] && printf "\e[0;95m$(ls $MAYA_TREE/pkg -p -1 | grep -v / | grep $2)\e[0m\n" && exit
 	;;
 	"--list-installed"|"-li") printf "\e[0;92m$(ls $MAYA_TREE/pkg/info -p -1)\e[0m\n" ;;
 	"--clean"|"-cl") rootCheck && rm -rf /tmp/maya ;;
 	"--sync-maya"|"-sy")
 		rootCheck
-		[[ -f /tmp/maya/maya ]] && rm -f /tmp/maya/maya
+		[[ -f /tmp/maya/maya.source ]] && rm -f /tmp/maya/maya.source
 		git clone https://github.com/sakaki91/maya /tmp/maya/maya.source
 		/usr/bin/install /tmp/maya/maya.source/maya /usr/local/bin/maya
 		/usr/bin/install /tmp/maya/maya.source/{README,LICENSE} /usr/local/share/maya/doc
-		/usr/bin/install /tmp/maya/maya.source/{pkg,src} /usr/local/share/maya/
-        ;;
-    	"--install"|"-in")
-        	binaryExCheck "$2"
+		cp -r /tmp/maya/maya.source/{pkg,src} /usr/local/share/maya/
+    ;;
+    "--install"|"-in")
+       	binaryExCheck "$2"
 		rootCheck
 		mkdir -p /tmp/maya && source "$MAYA_TREE/pkg/$2"
 		dependencieCheck && install && touch "$MAYA_TREE/pkg/info/$NAME"
-    	;;
-        "--remove"|"-rm")
+    ;;
+    "--remove"|"-rm")
 		binaryExCheck "$2"
 		rootCheck
-        	source "$MAYA_TREE/pkg/$2" && remove && rm -f "$MAYA_TREE/pkg/info/$NAME"
-    	;;
-    	*) printf "\e[0;91merror:\e[0m -h for help\n" ;;
+       	source "$MAYA_TREE/pkg/$2" && remove && rm -f "$MAYA_TREE/pkg/info/$NAME"
+    ;;
+    *) printf "\e[0;91merror:\e[0m -h for help\n" ;;
 esac
