Update 0.6
The main flow has been optimized, and a dependency selection has also been added before installations, and no... there were no skill issues today with $(pwd), I promise to pay more attention to that.

diff --git a/maya b/maya
--- a/maya
+++ b/maya
@@ -1,69 +1,62 @@
 #!/bin/bash
 
-# ESTE SOFTWARE ATUALMENTE ESTÁ EM ESTADO INICIAL DE DESENVOLVIMENTO, NÃO É RECOMENDADO O USO.
-# RECOMENDO O USO APENAS PARA FINS DE CONTRIBUIÇÃO, ESTUDOS E DEBUGGING.
-
-# MAYA_TREE="$(pwd)" # Diretorio improvisado para desenvolvimento, favor não alterar o diretorio padrão =D
-
-MAYA_VERSION=0.5-1
+MAYA_VERSION=0.6
 MAYA_TREE="$HOME/.local/share/maya"
 MAYA_TMP="/tmp/maya"
 [[ ! -d "$MAYA_TREE/pkg/info" ]] && mkdir -p "$MAYA_TREE/pkg/info"
 [[ ! -d "$MAYA_TMP" ]] && mkdir -p "$MAYA_TMP"
 
-function validate(){
+function validateDependencies(){
+    if [[ ! -z $DEPENDENCIES ]]; then
+        for dep in "${DEPENDENCIES[@]}"; do
+            if ! command -v "$dep" >/dev/null 2>&1; then
+                printf "\e[0;91merror:\033[0m $dep is not installed.\n" && exit
+            fi
+        done
+    fi
+}
+
+function validateBinaries(){
     [[ -z $1 ]] && printf "\e[0;91merror:\e[0m empty value.\n" && exit
     [[ ! -f "$MAYA_TREE/pkg/$1" ]] && printf "\e[0;91merror:\e[0m the package does not exist.\n" && exit
 }
 
 case $1 in
     "--help")
-        printf "\n\e[1m%-20s\e[0m %0s\n" "--help" "show this message."
+        printf "\e[1m%-20s\e[0m %0s\n" "--help" "show this message."
         printf "\e[1m%-20s\e[0m %0s\n\n" "--version" "shows the version."
         printf "\e[1m%-20s\e[0m %0s\n" "--search" "search and filter for the desired binaries."
         printf "\e[1m%-20s\e[0m %0s\n" "--about" "view the metadata (version, name, and description) of a package."
         printf "\e[1m%-20s\e[0m %0s\n" "--list" "shows all binaries available for installation."
         printf "\e[1m%-20s\e[0m %0s\n\n" "--list-installed" "it shows everything that maya has installed."
-        printf "\e[1m%-20s\e[0m %0s\n" "--clean" "clears the $MAYA_TMP directory (temporary directory where maya .tar files are stored)."
-        printf "\e[1m%-20s\e[0m %0s\n" "--sync-maya" "update maya and recipes by pulling directly from the git repository."
-        printf "\e[1m%-20s\e[0m %0s\n" "--install" "install something."
-        printf "\e[1m%-20s\e[0m %0s\n\n" "--remove" "remove something."
+        printf "\e[1m%-20s\e[0m %0s\n" "--clean" "clears the $MAYA_TMP directory."
+        printf "\e[1m%-20s\e[0m %0s\n" "--sync-maya" "update maya and recipes by pulling directly from the git."
+        printf "\e[1m%-20s\e[0m %0s\n" "--install" "install a binary."
+        printf "\e[1m%-20s\e[0m %0s\n" "--remove" "remove a binary."
     ;;
-    "--version") printf "\e[0;95mmaya-$MAYA_VERSION\e[0m\n" ;;
-    "--list-installed")
-    [[ ! $(ls "$MAYA_TREE/pkg/info") ]] && printf "\e[1mempty:\e[0m no binaries have been installed by maya (yet...)\e[0m\n" && exit
-        printf "\e[0;92m$(ls $MAYA_TREE/pkg/info -p -1)\e[0m\n"
-    ;;
+    "--version") printf "maya-$MAYA_VERSION\n" ;;
+    "--list-installed") printf "\e[0;92m$(ls $MAYA_TREE/pkg/info -p -1)\e[0m\n" ;;
     "--list") printf "\e[0;95m$(ls $MAYA_TREE/pkg -p -1 | grep -v /)\e[0m\n" ;;
     "--search")
-        [[ -z $1 ]] && printf "\e[0;91merror:\e[0m empty value.\n" && exit
+        [[ -z $2 ]] && printf "\e[0;91merror:\e[0m usage: maya --search 'name'\n" && exit
         printf "\e[0;95m$(ls $MAYA_TREE/pkg -p -1 | grep -v / | grep $2)\e[0m\n"
     ;;
-    "--about")
-        validate "$2"        
-        source "$MAYA_TREE/pkg/$2"
-        printf "\e[1m%-25s\e[0m %10s\n" "$NAME :: $VERSION" "$DESCRIPTION"
+    "--about") 
+        validateBinaries "$2"
+        source "$MAYA_TREE/pkg/$2" && printf "\e[1m%-25s\e[0m %10s\n" "$NAME :: $VERSION" "$DESCRIPTION"
     ;;
     "--sync-maya")
         [[ ! $(command -v git) ]] && printf "\e[0;91merror:\e[0m git not found\n." && exit
         (cd $MAYA_TREE && git pull)
     ;;
     "--install")
-        validate "$2"
-        source "$MAYA_TREE/pkg/$2"
-        install
-        touch "$MAYA_TREE/pkg/info/$NAME"
+        validateBinaries "$2"
+        source "$MAYA_TREE/pkg/$2" && validateDependencies && install && touch "$MAYA_TREE/pkg/info/$NAME"
     ;;
     "--remove")
-        validate "$2"
-        source "$MAYA_TREE/pkg/$2"
-        remove
-        rm -f "$MAYA_TREE/pkg/info/$NAME"
+        validateBinaries "$2"
+        source "$MAYA_TREE/pkg/$2" && remove && rm -f "$MAYA_TREE/pkg/info/$NAME"
     ;;
-    "--clean")
-        rm -rf "$MAYA_TMP" &>> /dev/null
-    ;;
-    *)
-        printf "lost? type: \e[1mmaya --help\e[0m\n"
-    ;;
+    "--clean") sudo rm -rf "$MAYA_TMP" ;;
+    *) printf ":: usage: \e[1mmaya --help\e[0m\n" ;;
 esac
