Update v1.0
So, we've arrived at the first major update!

Many things have changed in the inner workings of Maya, the main ones being:

* Migration from local user space ($HOME/.local/{share,bin}) to global
  space (/usr/local/{share,bin}), and now it has an automatic installation script (install.sh).

* And since it has been migrated to a global utility, the use of EUID=0 (root) is now strictly mandatory for operations; it works in the same way as any package manager, using both 'su -' and 'sudo'.

* With these changes, even the way recipes are synchronized has changed, and another very important thing was prioritizing the use of '/usr/bin/install [...]' instead of 'cp -r [...]' for clean installations.

* Therefore, ALL previous recipes have been updated accordingly, to follow the same logic, cleanliness, and visual consistency, and their dependency checks have also been reinforced.

Below is a list of what has changed:

added:
  install.sh

modified:
  maya
  pkg/cbonsai
  pkg/cmake
  pkg/discord
  pkg/fastfetch
  pkg/lsfg-vk
  pkg/make
  pkg/minecraft
  pkg/neofetch
  pkg/onefetch
  pkg/pfetch
  pkg/ren
  pkg/ufetch
  pkg/vault
  src/package-template.sh

diff --git a/maya b/maya
--- a/maya
+++ b/maya
@@ -1,61 +1,71 @@
 #!/bin/bash
 
-MAYA_VERSION=0.7
-MAYA_TREE="$HOME/.local/share/maya"
-MAYA_TMP="/tmp/maya"
-[[ ! -d "$MAYA_TREE/pkg/info" ]] && mkdir -p "$MAYA_TREE/pkg/info"
-[[ ! -d "$MAYA_TMP" ]] && mkdir -p "$MAYA_TMP"
+# Written by @sakaki91 (using VIM), heavily inspired by Ports.
 
-function validateDependencies(){
-    if [[ ! -z $DEPENDENCIES ]]; then
-        for dep in "${DEPENDENCIES[@]}"; do
-            if ! command -v "$dep" >/dev/null 2>&1; then
-                printf "\e[0;91merror:\033[0m $dep is not installed.\n" && exit
-            fi
-        done
-    fi
+MAYA_VERSION=1.0
+MAYA_TREE=/usr/local/share/maya
+
+function rootCheck(){
+	[[ $EUID != 0 ]] && printf "\e[0;91merror:\e[0m you can't run this without root access.\n" && exit
 }
 
-function validateBinaries(){
-    [[ -z $1 ]] && printf "\e[0;91merror:\e[0m empty value.\n" && exit
-    [[ ! -f "$MAYA_TREE/pkg/$1" ]] && printf "\e[0;91merror:\e[0m the package does not exist.\n" && exit
+function dependencieCheck(){
+	if [[ ! -z $DEPENDENCIES ]]; then
+        	for dep in "${DEPENDENCIES[@]}"; do
+	            if ! command -v "$dep" >/dev/null 2>&1; then
+        	        printf "\e[0;91merror:\033[0m $dep is not installed.\n" && exit
+	            fi
+        	done
+    	fi
+}
+
+function binaryExCheck(){
+	[[ -z $1 ]] && printf "\e[0;91merror:\e[0m empty value.\n" && exit
+	[[ ! -f "$MAYA_TREE/pkg/$1" ]] && printf "\e[0;91merror:\e[0m the package does not exist.\n" && exit
 }
 
 case $1 in
-    "--help"|"-h")
-        printf "\e[1moperations:\e[0m\n%-25s %0s\n" " -h  | --help" ":: show this message."
-        printf "%-25s %0s\n" " -v  | --version" ":: shows the version."
-        printf "%-25s %0s\n" " -a  | --about" ":: view the metadata (version, name, and description) of a package."
-        printf "%-25s %0s\n" " -l  | --list" ":: shows all binaries available for installation."
-        printf "%-25s %0s\n" " -li | --list-installed" ":: it shows everything that maya has installed."
-        printf "%-25s %0s\n" " -cl | --clean" ":: clears the $MAYA_TMP directory."
-        printf "%-25s %0s\n" " -sy | --sync-maya" ":: update maya and recipes by pulling directly from the git."
-        printf "%-25s %0s\n" " -in | --install" ":: install a binary."
-        printf "%-25s %0s\n\n" " -rm | --remove" ":: remove a binary."
-        printf "\e[1musage: maya 'operation' [...]\e[0m\n"
-    ;;
-    "--version"|"-v") printf "maya-$MAYA_VERSION\n" ;;
-    "--about"|"-a") 
-        validateBinaries "$2"
-        source "$MAYA_TREE/pkg/$2" && printf "\e[1m%-25s\e[0m %10s\n" "$NAME :: $VERSION" "$DESCRIPTION"
-    ;;
-    "--list"|"-l")
-        [[ -z $2 ]] && printf "\e[0;95m$(ls $MAYA_TREE/pkg -p -1 | grep -v /)\e[0m\n" && exit
-        [[ ! -z $2 ]] && printf "\e[0;95m$(ls $MAYA_TREE/pkg -p -1 | grep -v / | grep $2)\e[0m\n" && exit
-    ;;
-    "--list-installed"|"-li") printf "\e[0;92m$(ls $MAYA_TREE/pkg/info -p -1)\e[0m\n" ;;
-    "--clean"|"-cl") sudo rm -rf "$MAYA_TMP" ;;
-    "--sync-maya"|"-sy")
-        [[ ! $(command -v git) ]] && printf "\e[0;91merror:\e[0m git not found\n." && exit
-        (cd $MAYA_TREE && git pull)
-    ;;
-    "--install"|"-in")
-        validateBinaries "$2"
-        source "$MAYA_TREE/pkg/$2" && validateDependencies && install && touch "$MAYA_TREE/pkg/info/$NAME"
-    ;;
-    "--remove"|"-rm")
-        validateBinaries "$2"
-        source "$MAYA_TREE/pkg/$2" && remove && rm -f "$MAYA_TREE/pkg/info/$NAME"
-    ;;
-    *) printf "\e[0;93m::\e[0m usage: \e[1mmaya --help\e[0m\n" ;;
+	"--help"|"-h")
+		printf "\e[1moperations:\e[0m\n%-25s %0s\n" " -h  | --help" ":: show this message."
+	        printf "%-25s %0s\n" " -v  | --version" ":: shows the version."
+        	printf "%-25s %0s\n" " -a  | --about" ":: view the metadata (version, name, and description) of a package."
+	        printf "%-25s %0s\n" " -l  | --list" ":: shows all binaries available for installation."
+        	printf "%-25s %0s\n" " -li | --list-installed" ":: it shows everything that maya has installed."
+	        printf "%-25s %0s\n" " -cl | --clean" ":: clears the /tmp/maya directory."
+        	printf "%-25s %0s\n" " -sy | --sync-maya" ":: update maya and recipes by pulling directly from the git."
+	        printf "%-25s %0s\n" " -in | --install" ":: install a binary."
+        	printf "%-25s %0s\n\n" " -rm | --remove" ":: remove a binary."
+	        printf "\e[1musage: maya 'operation' [...]\e[0m\n"
+    	;;
+    	"--version"|"-v") printf "maya-$MAYA_VERSION\n" ;;
+    	"--about"|"-a") 
+     		binaryExCheck "$2"
+	        source "$MAYA_TREE/pkg/$2" && printf "\e[1m%-25s\e[0m %10s\n" "$NAME :: $VERSION" "$DESCRIPTION"
+    	;;
+    	"--list"|"-l") 
+	    	[[ -z $2 ]] && printf "\e[0;95m$(ls $MAYA_TREE/pkg -p -1 | grep -v /)\e[0m\n" && exit
+	    	[[ ! -z $2 ]] && printf "\e[0;95m$(ls $MAYA_TREE/pkg -p -1 | grep -v / | grep $2)\e[0m\n" && exit
+	;;
+	"--list-installed"|"-li") printf "\e[0;92m$(ls $MAYA_TREE/pkg/info -p -1)\e[0m\n" ;;
+	"--clean"|"-cl") rootCheck && rm -rf /tmp/maya ;;
+	"--sync-maya"|"-sy")
+		rootCheck
+		[[ -f /tmp/maya/maya ]] && rm -f /tmp/maya/maya
+		git clone https://github.com/sakaki91/maya /tmp/maya/maya.source
+		/usr/bin/install /tmp/maya/maya.source/maya /usr/local/bin/maya
+		/usr/bin/install /tmp/maya/maya.source/{README,LICENSE} /usr/local/share/maya/doc
+		/usr/bin/install /tmp/maya/maya.source/{pkg,src} /usr/local/share/maya/
+        ;;
+    	"--install"|"-in")
+        	binaryExCheck "$2"
+		rootCheck
+		mkdir -p /tmp/maya && source "$MAYA_TREE/pkg/$2"
+		dependencieCheck && install && touch "$MAYA_TREE/pkg/info/$NAME"
+    	;;
+        "--remove"|"-rm")
+		binaryExCheck "$2"
+		rootCheck
+        	source "$MAYA_TREE/pkg/$2" && remove && rm -f "$MAYA_TREE/pkg/info/$NAME"
+    	;;
+    	*) printf "\e[0;91merror:\e[0m -h for help\n" ;;
 esac
